[package]
name = "cgol"
version = "0.1.0"
edition = "2024"

[dependencies]
js-sys = "0.3.105"
wasm-bindgen = "0.2.128"
web-sys = { version = "0.3.105", features = ["CanvasRenderingContext2d", "Document", "DomWindowResizeEventDetail", "Event", "HtmlCanvasElement", "Window", "console"] }


[lib]
crate-type = ["cdylib", "rlib"]
